### ISSUE TITLE
use MSBuild.Community.Tasks.dll from NuGet packages folder

### ISSUE THREAD

**Issue by frogger3d** [loresoft/msbuildtasks#144]
The NuGet package copies the .dll and .targets to a .build folder at the top of the solution. The problem is that both files need to be included in source control. The reason for this is that they are only placed there when the NuGet package is installed/updated, not when it is fetched.

We could probably use MSBuild Transforms to include both the targets and the dll file from the Packages folder.

**Comment by Zoltu** [comment]
Fixed in https://github.com/loresoft/msbuildtasks/pull/158

**Comment by vchekan** [comment]
+1. The whole point of nuget is not to commit binaries to source code repository.
