### ISSUE TITLE
FileUpdate no longer supports output property "NotUpdatedItems"

### ISSUE THREAD

**Issue by ynauls** [loresoft/msbuildtasks#156]
Recently upgraded from 1.3.0.503 to 1.4.x and FileUpdate task no longer supports Output properties ExitCode and NotUpdatedItems. Is this by design or a bad merge?

**Comment by aolszowka** [comment]
It'd be unusual to remove functionality I'm on mobile right now but I'd be happy to look when I'm back next week if someone else hasn't looked into it yet.

**Comment by piolo108** [comment]
Sounds good, below is the usage of the task in a target

```
<CreateItem Include="$(SomeFolder)\**\*.sql">
            <Output TaskParameter="Include" ItemName="ValidateFiles"/>
</CreateItem>        
        
<FileUpdate Files="@(ValidateFiles)" Regex="\$\(SomeToken\)" ReplacementText="SomeValue">
            <Output TaskParameter="NotUpdatedItems" ItemName="NotUpdatedItems"/>
            <Output TaskParameter="ExitCode" PropertyName="ExitCode"/>
</FileUpdate>
                
<Error Text="The following were not updated. Scripts: @(NotUpdatedItems)" Condition="$(ExitCode) == 'False'"/>
```

**Comment by piolo108** [comment]
*Update*, I am not 100% sure, but I might have added that logic to the task way back in the day.  I added the logic to my forked repo, I will submit a pull request for your evaluation.

**Comment by ynauls** [comment]
What's the roadmap to push these changes to Nuget?
