### ISSUE TITLE
Mono 4 support

### ISSUE THREAD

**Issue by lukebakken** [loresoft/msbuildtasks#184]
Hello!

I have been using this library in the Riak .NET Client but have run into the following incompatibility with Mono 4 ([build log](https://travis-ci.org/basho/riak-dotnet-client/builds/82740464)):

```
Project "/home/travis/build/basho/riak-dotnet-client/build/build.targets" (UnitTest target(s)):
    Target SetupTests:
: error : Error initializing task XmlQuery: Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
        Build FAILED.
        Errors:
        /home/travis/build/basho/riak-dotnet-client/build/build.targets (UnitTest) ->
        (SetupTests target) ->
            : error : Error initializing task XmlQuery: Could not load file or assembly 'Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
             0 Warning(s)
             1 Error(s)
        Time Elapsed 00:00:00.1108750
make: *** [unit-test] Error 1
```

This is apparently due to incompatible changes between Mono 3 and Mono 4.

Is there interest in adding full Mono support to this library? In other words, a PR that would allow a user to clone this repo and build on Mono 4.

**Comment by roman-yagodin** [comment]
Vote for it!

AFAIK Mono 4 have Mono Microsoft.Build.Utilities.v4.0 (libmono-microsoft-build-utilities-v4.0-4.0-cil package on Debian).

**Comment by pwelter34** [comment]
There is a pending change to move to .net 4, IE v4.0 of the library.  However, I haven't come up with a way to support old msbuild and new msbuild quite yet.  I'm happy to just move to .net 4 only, but i don't want to break others.  Ideas?

**Comment by lukebakken** [comment]
If a user needs support for older .NET versions, use an older version of `msbuildtasks` ?

**Comment by roman-yagodin** [comment]
It's a common sense, but if there is a way to build against various .NET versions (?), then shipping several binary versions for each release would do the job.

**Comment by slide** [comment]
Anyone have a fix for this? I would love to be able to build on mono!
