### ISSUE TITLE
FtpUpload task hardcoded timeout issue

### ISSUE THREAD

**Issue by pvones** [loresoft/msbuildtasks#20]
FtpUpload tasks sometimes fails because of short hardcoded timeout 7000 ms (FtpUpload.cs source file). Please add task parameter to specify the timeout.

**Comment by ozankiraz** [comment]
@pvones . I can see the public parameter, have you set it in your msbuild task call like Timeout="60000" or something like that?

https://github.com/loresoft/msbuildtasks/blob/fcdca441dece36d3d49ea7c04de6795acebcb2c2/Source/MSBuild.Community.Tasks/FtpUpload/FtpUpload.cs#L201
