### ISSUE TITLE
NUnit 3.0 Support

### ISSUE THREAD

**Issue by stevewi1950** [loresoft/msbuildtasks#201]
The MSBuild Task, NUnit does not support the new version of NUnit (3.0.x) as the nunit-console.exe executable has been renamed to nunit3-console.exe within the 3.0.x release.  

I have verified that the NUnit 3.0 tests can be run through the MSBuild Tasks by created a new task locally, calling it NUnit3 and altered the code to call the correct executable (with the correct flags etc).

**Comment by shatl** [comment]
+1

**Comment by temporafugiunt** [comment]
+2

**Comment by temporafugiunt** [comment]
NUnit 3 doesn't appear to support the /noshadow command anymore either.

**Comment by stevewi1950** [comment]
I will put a pull request together with my changes when I get a chance.  I believe the /noshadow is not supported as this is how it runs by default (don't quote me on that, see the nunit project for details) as there is a --shadowcopy parameter to enable shadow copy.

**Comment by ChrisMaddock** [comment]
Have just hit the same problem - thank you for looking at it @stevewi1950. Look forward to seeing this live.

**Comment by temporafugiunt** [comment]
For the shadow copy option, it appears you are correct and they inverted it for nunit 3.

https://github.com/nunit/nunit/issues/521

For the console, by default the shadow copy feature is disabled and you now have an option to enable shadow copy.

**Comment by stevewi1950** [comment]
Thanks @temporafugiunt for that.  I was just looking this up and noticed that you added the reference to the NUnit 3.0 issue.

**Comment by stevewi1950** [comment]
Pull Request #205 covers the mods for this issue.

**Comment by stevewi1950** [comment]
Addressed by pull request #205
