### ISSUE TITLE
GitVersion failed unexpectedly with MethodAccessException ... strong-name

### ISSUE THREAD

**Issue by joshgo** [loresoft/msbuildtasks#222]
Hi,

I followed the steps in this article http://nowfromhome.com/msbuild-add-git-commit-hash-to-assemblyinfo/ . It's pretty straightforward, but I got a methodaccess error. The error messages I received are as follows:

error MSB4018: The "GitVersion" task failed unexpectedly.
error MSB4018: System.MethodAccessException:  Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
error MSB4018:    at MSBuild.Community.Tasks.Git.GitClient.ValidateParameters()

I couldn't find anything in the issues list, and was not having much success searching on Google. 

Is this an issue? Or am I using msbuildtasks incorrectly? If so, could someone point me in the right direction?

Thanks,
Josh

**Comment by DavidLievrouw** [comment]
Same here. 

Something to do with strong name: http://stackoverflow.com/questions/10738008/accessing-newly-signed-third-party-dll-gives-error

I don't get this error when I build master locally, without strong name.

**Comment by joshgo** [comment]
Yeah, I did the same thing and built off master. Thanks for the link.

**Comment by joshgo** [comment]
Fixed by #223
