### ISSUE TITLE
TfsClient task fails on VS 2017

### ISSUE THREAD

**Issue by Eagle3386** [loresoft/msbuildtasks#281]
The [candidates](https://github.com/loresoft/msbuildtasks/blob/6196d43e7eb6807f306e9861b286fe61c8bb0993/Source/MSBuild.Community.Tasks/Tfs/TfsClient.cs#L225) for `tf.exe`'s paths neither contain an entry for VS 2017 nor does the previous scheme (`C:\Program Files (x86)\Microsoft Visual Studio <VS version>.0\Common7\IDE`) work from this version onwards (according to MS).

Instead, the new path - depending on the user's VS edition - looks like this:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\<edition>\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer`

Valid example:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer`

I've created a (hopefully future-proof) PR to fix this. Please review and merge or suggest improvements.

**Comment by Eagle3386** [comment]
@pwelter34, are you able to have a look at the PR and eventually merge this in the next couple of days?

**Comment by aolszowka** [comment]
Because TfsClient simply extends ToolTask you should be able to Override ToolPath in your MsBuild Script (the PR will obviously fix the auto-magic discovery):

`<TfsClient ToolPath="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer"/>`

Until the PR is merged.

**Comment by Eagle3386** [comment]
> Because TfsClient simply extends ToolTask you should be able to Override ToolPath in your MsBuild Script (the PR will obviously fix the auto-magic discovery):
>  (...)

Thanks a lot for the hint! Will use it until merge completes..
